[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mongodb = "2.4.0"
rand = "0.8.5"
serde = "1.0.159"

[dependencies.serenity]
version = "0.11.5"
features = ["model", "collector"]

[dependencies.tokio]
version = "1"
features = ["full"]
